- hosts: backend_servers
  tasks:
          - name: "installing httpd"
            package:
                    name: "httpd"
                    state: present

          - name: "installing php software"
            package:
                    name: "php"
                    state: present

          - name: "copying webpage"
            copy:
                    src: "/etc/ansible/mypage.php"
                    dest: "/var/www/html"

          - name: "starting service"
            service:
                    name: "httpd"
                    state: started
